let alertsEnabled=true,soundEnabled=true,seenSignals=new Set(),alertCount=0,audioCtx=null;
function getAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();return audioCtx;}
function playBeep(freq,dur,type='sine',vol=0.3){try{const ctx=getAudio(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.setValueAtTime(freq,ctx.currentTime);osc.type=type;gain.gain.setValueAtTime(vol,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+dur);osc.start(ctx.currentTime);osc.stop(ctx.currentTime+dur);}catch(e){}}
function playBuySound(){playBeep(523,.12,'sine',.25);setTimeout(()=>playBeep(659,.12,'sine',.25),130);setTimeout(()=>playBeep(784,.20,'sine',.30),260);}
function playSellSound(){playBeep(784,.12,'sine',.25);setTimeout(()=>playBeep(659,.12,'sine',.25),130);setTimeout(()=>playBeep(523,.20,'sine',.30),260);}
function playMetalSound(){playBeep(880,.08,'triangle',.2);setTimeout(()=>playBeep(1100,.08,'triangle',.2),100);setTimeout(()=>playBeep(1320,.15,'triangle',.25),200);setTimeout(()=>playBeep(1760,.25,'sine',.3),320);}
function showToast(signal){
  const isMetal=signal.sym==='XAUUSD'||signal.sym==='XAGUSD';
  const isBuy=signal.dir==='buy';
  const color=isMetal?'#ffcc00':isBuy?'#00ff88':'#ff2244';
  const icon=isMetal?'⬡':isBuy?'▲':'▼';
  const bg=isMetal?'rgba(26,16,0,0.97)':isBuy?'rgba(0,20,10,0.97)':'rgba(26,0,6,0.97)';
  const t=document.createElement('div');
  t.style.cssText=`position:fixed;bottom:24px;right:24px;z-index:9999;background:${bg};border:1px solid ${color};border-left:4px solid ${color};border-radius:10px;padding:14px 18px;min-width:260px;max-width:320px;box-shadow:0 8px 32px rgba(0,0,0,0.6);animation:toastIn .3s cubic-bezier(.34,1.56,.64,1) forwards;cursor:pointer;`;
  t.innerHTML=`<div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><span style="font-size:20px">${icon}</span><div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:700;color:#fff;letter-spacing:1px">${signal.pair} — ${signal.dir.toUpperCase()}</div><div style="font-size:10px;color:${color};font-family:'Space Mono',monospace;letter-spacing:1.5px">${signal.tf} · AI SIGNAL · ${signal.confidence}% CONF</div></div><button onclick="this.parentElement.parentElement.remove()" style="margin-left:auto;background:none;border:none;color:#3a5888;font-size:18px;cursor:pointer">×</button></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px;font-family:'Space Mono',monospace;font-size:10px"><div style="background:rgba(255,255,255,0.05);padding:6px 8px;border-radius:5px"><div style="color:#3a5888;font-size:8px;margin-bottom:2px">ENTRY</div><div style="color:#fff;font-weight:700">${signal.entry}</div></div><div style="background:rgba(0,255,136,0.08);padding:6px 8px;border-radius:5px"><div style="color:#3a5888;font-size:8px;margin-bottom:2px">TP</div><div style="color:#00ff88;font-weight:700">${signal.tp}</div></div><div style="background:rgba(255,34,68,0.08);padding:6px 8px;border-radius:5px"><div style="color:#3a5888;font-size:8px;margin-bottom:2px">SL</div><div style="color:#ff2244;font-weight:700">${signal.sl}</div></div></div><div style="margin-top:8px;font-size:9px;color:#3a5888;font-family:'Space Mono',monospace">RR ${signal.rr} · ${signal.duration}</div>`;
  document.body.appendChild(t);
  setTimeout(()=>{if(t.parentElement){t.style.animation='toastOut .3s ease forwards';setTimeout(()=>t.remove(),300);}},8000);
  t.onclick=()=>t.remove();
}
function sendBrowserNotification(signal){if(!('Notification'in window)||Notification.permission!=='granted')return;try{const n=new Notification(`ForexAI Pro — ${signal.pair} ${signal.dir.toUpperCase()}`,{body:`Entry: ${signal.entry} | TP: ${signal.tp} | SL: ${signal.sl}`,tag:'forexai'});setTimeout(()=>n.close(),6000);}catch(e){}}
function triggerAlert(signal){if(!alertsEnabled)return;const key=signal.sym+signal.dir+signal.entry;if(seenSignals.has(key))return;seenSignals.add(key);alertCount++;updateAlertBadge();if(soundEnabled){const m=signal.sym==='XAUUSD'||signal.sym==='XAGUSD';if(m)playMetalSound();else if(signal.dir==='buy')playBuySound();else playSellSound();}showToast(signal);sendBrowserNotification(signal);fetch("/api/telegram",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(signal)}).catch(e=>console.warn("[Telegram]",e.message));console.log('[Alert]',signal.pair,signal.dir.toUpperCase());}
function alertNewSignals(signals){if(!signals||!signals.length)return;signals.forEach((s,i)=>setTimeout(()=>triggerAlert(s),i*600));}
function updateAlertBadge(){const b=document.getElementById('alertBadge');if(b){b.textContent=alertCount;b.style.display=alertCount>0?'flex':'none';}}
function showMiniToast(msg){const t=document.createElement('div');t.style.cssText='position:fixed;bottom:90px;right:24px;z-index:9999;background:rgba(6,13,31,0.95);border:1px solid rgba(0,212,255,0.3);border-radius:6px;padding:8px 14px;font-family:Space Mono,monospace;font-size:11px;color:#00d4ff;';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2000);}
function toggleAlerts(){alertsEnabled=!alertsEnabled;const b=document.getElementById('alertBellBtn');if(b){b.style.color=alertsEnabled?'var(--accent)':'var(--text3)';b.style.borderColor=alertsEnabled?'rgba(0,212,255,0.4)':'rgba(255,255,255,0.1)';}showMiniToast(alertsEnabled?'🔔 Alerts ON':'🔕 Alerts OFF');}
function toggleSound(){soundEnabled=!soundEnabled;const b=document.getElementById('soundBtn');if(b)b.textContent=soundEnabled?'🔊':'🔇';showMiniToast(soundEnabled?'🔊 Sound ON':'🔇 Sound OFF');}
function testAlert(){seenSignals.clear();triggerAlert({pair:'EUR/USD',sym:'EURUSD',dir:'buy',tf:'M15',entry:'1.15610',tp:'1.15720',sl:'1.15550',confidence:91,rr:'1:1.8',duration:'15-20 min'});setTimeout(()=>{seenSignals.clear();triggerAlert({pair:'XAU/USD',sym:'XAUUSD',dir:'buy',tf:'M15',entry:'5174.50',tp:'5182.50',sl:'5169.50',confidence:92,rr:'1:1.6',duration:'15-20 min'});},900);}
function injectAlertStyles(){const s=document.createElement('style');s.textContent=`@keyframes toastIn{from{opacity:0;transform:translateX(40px) scale(.95)}to{opacity:1;transform:translateX(0) scale(1)}}@keyframes toastOut{from{opacity:1}to{opacity:0;transform:translateX(40px)}}#alertBellBtn{background:rgba(0,212,255,0.08);border:1px solid rgba(0,212,255,0.4);color:var(--accent);font-size:16px;width:34px;height:34px;border-radius:7px;cursor:pointer;transition:all .2s;display:flex;align-items:center;justify-content:center;}#alertBellBtn:hover{background:rgba(0,212,255,0.15);}#soundBtn{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);font-size:14px;width:34px;height:34px;border-radius:7px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all .2s;}#testAlertBtn{background:rgba(255,204,0,0.08);border:1px solid rgba(255,204,0,0.3);color:#ffcc00;font-family:var(--cond);font-size:11px;font-weight:700;letter-spacing:1.5px;padding:0 12px;height:34px;border-radius:7px;cursor:pointer;white-space:nowrap;}.alert-bell-wrap{position:relative;display:inline-flex;align-items:center;}#alertBadge{position:absolute;top:-6px;right:-6px;background:var(--red);color:#fff;font-size:8px;font-weight:700;width:16px;height:16px;border-radius:50%;display:none;align-items:center;justify-content:center;border:2px solid var(--bg);}`;document.head.appendChild(s);}
function injectAlertButtons(){const h=document.querySelector('.header-right');if(!h)return;const w=document.createElement('div');w.style.cssText='display:flex;align-items:center;gap:6px;margin-right:8px;';w.innerHTML=`<button id="testAlertBtn" onclick="testAlert()">⚡ TEST</button><button id="soundBtn" onclick="toggleSound()">🔊</button><div class="alert-bell-wrap"><button id="alertBellBtn" onclick="toggleAlerts()">🔔</button><span id="alertBadge">0</span></div>`;h.insertBefore(w,h.firstChild);}
function initAlerts(){injectAlertStyles();injectAlertButtons();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();}
document.addEventListener('DOMContentLoaded',initAlerts);
