const PRICES={EURUSD:'--',GBPUSD:'--',USDJPY:'--',AUDUSD:'--',USDCAD:'--',USDCHF:'--',EURGBP:'--',NZDUSD:'--',XAUUSD:'--',XAGUSD:'--'};
const DIRS={};
const DEFAULTS={EURUSD:'1.15610',GBPUSD:'1.33356',USDJPY:'157.920',AUDUSD:'0.70062',USDCAD:'1.36510',USDCHF:'0.78237',EURGBP:'0.86692',NZDUSD:'0.58723',XAUUSD:'5174.50',XAGUSD:'32.341'};
function seedDefaults(){Object.keys(DEFAULTS).forEach(k=>{if(PRICES[k]==='--'){PRICES[k]=DEFAULTS[k];DIRS[k]='up';}});}
async function fetchAllPrices(){try{const r=await fetch('/api/prices');const d=await r.json();if(!d||d.error)throw new Error(d?.error||'no data');['EURUSD','GBPUSD','USDJPY','AUDUSD','USDCAD','USDCHF','EURGBP','NZDUSD','XAUUSD','XAGUSD'].forEach(sym=>{if(d[sym])setPrice(sym,d[sym]);});console.log('[Prices] Gold:$'+PRICES.XAUUSD+' | Silver:$'+PRICES.XAGUSD+' | EUR/USD:'+PRICES.EURUSD);buildSignals();}catch(e){console.warn('[Prices] Server error:'+e.message);startSimulation();}}
function setPrice(sym,price){const prev=parseFloat(PRICES[sym]);const curr=parseFloat(price);if(isNaN(curr)||curr<=0)return;DIRS[sym]=(isNaN(prev)||curr>=prev)?'up':'dn';PRICES[sym]=String(price);updateTickerItem(sym);updateCardPrice(sym);updateSignalLevels(sym);}
function updateTickerItem(sym){const el=document.getElementById('tp-'+sym);if(!el)return;el.textContent=PRICES[sym];const arr=el.parentElement?.querySelector('.t-arr');if(arr){arr.textContent=DIRS[sym]==='dn'?'▼':'▲';arr.className='t-arr '+(DIRS[sym]==='dn'?'t-dn':'t-up');}}
function updateCardPrice(sym){const el=document.getElementById('cp-'+sym);if(!el)return;el.textContent=PRICES[sym];el.className='pair-price '+(DIRS[sym]==='dn'?'dn':'up');}
function updateSignalLevels(sym){const def=SIGNAL_DEFS.find(s=>s.sym===sym);const lv=calcLevels(sym,def?.dir||'buy');['entry','tp','sl'].forEach(t=>{const el=document.getElementById('lv-'+t+'-'+sym);if(el&&lv[t]!=='--')el.textContent=lv[t];});}
function startSimulation(){seedDefaults();setInterval(()=>{[['EURUSD',5],['GBPUSD',5],['AUDUSD',5],['NZDUSD',5],['EURGBP',5]].forEach(([s,d])=>setPrice(s,(parseFloat(PRICES[s])+(Math.random()-.48)*0.00012).toFixed(d)));setPrice('USDJPY',(parseFloat(PRICES.USDJPY)+(Math.random()-.48)*0.008).toFixed(3));['USDCAD','USDCHF'].forEach(s=>setPrice(s,(parseFloat(PRICES[s])+(Math.random()-.48)*0.00012).toFixed(5)));setPrice('XAUUSD',(parseFloat(PRICES.XAUUSD)+(Math.random()-.48)*0.80).toFixed(2));setPrice('XAGUSD',(parseFloat(PRICES.XAGUSD)+(Math.random()-.48)*0.015).toFixed(3));},1500);}
function calcLevels(sym,dir){const raw=parseFloat(PRICES[sym]);if(!raw||raw<=0||isNaN(raw))return{entry:'--',tp:'--',sl:'--'};let tpD,slD,dec;if(sym==='XAUUSD'){tpD=8.00;slD=5.00;dec=2;}else if(sym==='XAGUSD'){tpD=0.20;slD=0.12;dec=3;}else if(sym==='USDJPY'){tpD=0.130;slD=0.080;dec=3;}else{tpD=0.00100;slD=0.00060;dec=5;}const e=parseFloat(raw.toFixed(dec));return{entry:e.toFixed(dec),tp:(dir==='buy'?e+tpD:e-tpD).toFixed(dec),sl:(dir==='buy'?e-slD:e+slD).toFixed(dec)};}
const SIGNAL_DEFS=[
  {pair:'EUR/USD',sym:'EURUSD',dir:'buy', tf:'M15',ai:91,rr:'1:1.7',ind:['EMA9','EMA21','RSI','MACD'],time:'09:14',dur:'15–25 min',trend:[1,1,1,0,1,1,1,1,0,1,1,1]},
  {pair:'GBP/USD',sym:'GBPUSD',dir:'buy', tf:'M30',ai:88,rr:'1:1.8',ind:['MACD','VWAP','BB'],time:'08:52',dur:'20–30 min',trend:[1,1,0,1,1,1,0,1,1,1,1,1]},
  {pair:'USD/JPY',sym:'USDJPY',dir:'sell',tf:'M15',ai:85,rr:'1:1.6',ind:['RSI','EMA','MACD'],time:'07:30',dur:'15–20 min',trend:[0,0,1,0,0,0,1,0,0,0,0,0]},
  {pair:'AUD/USD',sym:'AUDUSD',dir:'buy', tf:'M30',ai:86,rr:'1:1.7',ind:['EMA','RSI','BB'],time:'08:10',dur:'20–30 min',trend:[1,1,1,0,0,1,1,1,1,0,1,1]},
  {pair:'USD/CAD',sym:'USDCAD',dir:'sell',tf:'M15',ai:89,rr:'1:1.7',ind:['MACD','EMA21','RSI'],time:'07:55',dur:'15–25 min',trend:[0,0,0,1,0,0,0,0,1,0,0,0]},
  {pair:'EUR/GBP',sym:'EURGBP',dir:'sell',tf:'M30',ai:83,rr:'1:1.8',ind:['RSI','MACD','BB'],time:'09:02',dur:'20–30 min',trend:[0,0,1,0,0,0,0,1,0,0,0,0]},
  {pair:'XAU/USD',sym:'XAUUSD',dir:'buy', tf:'M15',ai:92,rr:'1:1.6',ind:['EMA9','EMA21','RSI','VWAP'],time:'08:00',dur:'15–20 min',trend:[1,1,1,1,0,1,1,1,1,1,0,1],metal:true},
  {pair:'XAG/USD',sym:'XAGUSD',dir:'buy', tf:'M30',ai:87,rr:'1:1.8',ind:['RSI','VWAP','EMA21','BB'],time:'08:35',dur:'20–30 min',trend:[1,1,0,1,1,1,1,0,1,1,1,1],metal:true},
];
let currentFilter='ALL';
function buildSignals(filter){if(filter)currentFilter=filter;const grid=document.getElementById('signalsGrid');if(!grid)return;let list=SIGNAL_DEFS;if(currentFilter==='BUY')list=list.filter(s=>s.dir==='buy');if(currentFilter==='SELL')list=list.filter(s=>s.dir==='sell');if(currentFilter==='METALS')list=list.filter(s=>s.metal);grid.innerHTML=list.map((s,i)=>{const lv=calcLevels(s.sym,s.dir);const price=PRICES[s.sym]!=='--'?PRICES[s.sym]:DEFAULTS[s.sym];const cls=s.metal?`sig-card metal-${s.dir}`:`sig-card ${s.dir}`;const iCls=s.metal?'pair-icon metal':'pair-icon';const mBadge=s.metal?`<span class="metal-tag">${s.pair==='XAU/USD'?'⬡ GOLD':'◇ SILVER'}</span>`:'';const trend=s.trend.map(v=>`<div class="trend-pip" style="background:${v?(s.metal?'var(--gold)':'var(--green)'):'var(--red)'};opacity:${v?.8:.4}"></div>`).join('');return`<div class="${cls}" style="animation-delay:${i*.07}s"><div class="c-hdr"><div class="pair-info"><div class="${iCls}">${s.pair.replace('/','<br>')}</div><div><div class="pair-name">${s.pair}${mBadge}</div><div class="pair-price ${DIRS[s.sym]||'up'}" id="cp-${s.sym}">${price}</div></div></div><div class="c-badge"><span class="dir-badge ${s.dir}">${s.dir.toUpperCase()}</span><span class="c-tf">${s.tf}·${s.time}GMT</span></div></div><div class="c-body"><div class="levels"><div class="level"><div class="lv-label">Entry</div><div class="lv-val entry" id="lv-entry-${s.sym}">${lv.entry}</div></div><div class="level"><div class="lv-label">Take Profit</div><div class="lv-val tp" id="lv-tp-${s.sym}">${lv.tp}</div></div><div class="level"><div class="lv-label">Stop Loss</div><div class="lv-val sl" id="lv-sl-${s.sym}">${lv.sl}</div></div></div><div class="conf-box"><div class="conf-row"><span class="conf-label"><span class="ai-chip">AI</span> Confidence</span><span class="conf-pct">${s.ai}%</span></div><div class="conf-bar"><div class="conf-fill" style="width:${s.ai}%"></div></div></div><div class="trend-row">${trend}</div></div><div class="c-footer"><div class="tags">${s.ind.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="c-meta"><span class="rr-val">RR ${s.rr}</span><span class="dur-val">⏱${s.dur}</span></div></div></div>`;}).join('');}
function filterSignals(type,btn){document.querySelectorAll('.filter-btn,.f-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');buildSignals(type);}
const HISTORY=[{pair:'EUR/USD',dir:'buy',tf:'M15',entry:'1.15480',tp:'1.15580',sl:'1.15420',res:'WIN',pips:'+10',time:'08:30'},{pair:'XAU/USD',dir:'buy',tf:'M15',entry:'5155.00',tp:'5163.00',sl:'5150.00',res:'WIN',pips:'+80',time:'07:45'},{pair:'GBP/USD',dir:'sell',tf:'M30',entry:'1.33420',tp:'1.33280',sl:'1.33500',res:'WIN',pips:'+14',time:'07:10'},{pair:'USD/JPY',dir:'buy',tf:'M15',entry:'157.820',tp:'157.950',sl:'157.740',res:'LOSS',pips:'-8',time:'06:50'},{pair:'XAG/USD',dir:'buy',tf:'M30',entry:'32.180',tp:'32.380',sl:'32.070',res:'WIN',pips:'+20',time:'06:20'},{pair:'EUR/GBP',dir:'sell',tf:'M15',entry:'0.84010',tp:'0.83900',sl:'0.84070',res:'WIN',pips:'+11',time:'05:55'},{pair:'AUD/USD',dir:'buy',tf:'M30',entry:'0.63180',tp:'0.63280',sl:'0.63120',res:'LOSS',pips:'-6',time:'05:30'},{pair:'EUR/USD',dir:'sell',tf:'M15',entry:'1.15720',tp:'1.15620',sl:'1.15780',res:'WIN',pips:'+10',time:'04:45'}];
function buildHistory(){const tb=document.getElementById('historyBody');if(!tb)return;tb.innerHTML=HISTORY.map(h=>`<tr><td style="color:#fff;font-weight:700">${h.pair}</td><td class="${h.dir==='buy'?'buy-d':'sell-d'}">${h.dir.toUpperCase()}</td><td>${h.tf}</td><td>${h.entry}</td><td style="color:var(--green)">${h.tp}</td><td style="color:var(--red)">${h.sl}</td><td class="${h.res==='WIN'?'win':'loss'}">${h.res}</td><td class="${h.res==='WIN'?'win':'loss'}">${h.pips}</td><td>${h.time}GMT</td></tr>`).join('');}
function buildTicker(){const track=document.getElementById('tickerTrack');if(!track)return;const items=[{sym:'EURUSD',label:'EUR/USD'},{sym:'GBPUSD',label:'GBP/USD'},{sym:'USDJPY',label:'USD/JPY'},{sym:'AUDUSD',label:'AUD/USD'},{sym:'USDCAD',label:'USD/CAD'},{sym:'USDCHF',label:'USD/CHF'},{sym:'EURGBP',label:'EUR/GBP'},{sym:'NZDUSD',label:'NZD/USD'},{sym:'XAUUSD',label:'XAU/USD'},{sym:'XAGUSD',label:'XAG/USD'}];track.innerHTML=[...items,...items].map(it=>`<span class="t-item"><span class="t-pair">${it.label}</span><span class="t-price" id="tp-${it.sym}">${PRICES[it.sym]}</span><span class="t-arr t-up">▲</span></span>`).join('');}
function updateSession(){const h=new Date().getUTCHours();let s='SYDNEY SESSION';if(h>=7&&h<16)s='LONDON SESSION';if(h>=12&&h<21)s='NEW YORK SESSION';if(h>=23||h<7)s='TOKYO SESSION';const el=document.getElementById('sessionBadge');if(el)el.textContent=s;}
function initSignals(){seedDefaults();buildTicker();buildSignals();buildHistory();updateSession();setInterval(updateSession,60000);fetchAllPrices();setInterval(fetchAllPrices,15000);}
document.addEventListener('DOMContentLoaded',initSignals);
